CREATE TABLE EMP(
    EMPNO INTEGER NOT NULL,
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR INTEGER,
    HIREDATE VARCHAR(12),
    SAL DECIMAL(7, 2),
    COMM DECIMAL(7, 2),
    DEPTNO INTEGER
);